### ISSUE TITLE
Internal server error(405) when user tries to edit a new created user

### ISSUE THREAD

**Issue by atarason** [IrynaZavushchak/EPlast#14]
![image](https://user-images.githubusercontent.com/7124012/81932466-8b4f2480-95f4-11ea-9e62-57932d0adc15.png)

The same issue is when user tries to edit profile from setting icon of header

![image](https://user-images.githubusercontent.com/7124012/81933595-5643d180-95f6-11ea-85df-5526b2b0ea69.png)

**Comment by VolodymyrVerm** [comment]
It has already been redesigned, but not deployed

**Comment by atarason** [comment]
ok, that's fine. Please, could you re-test after deploy? if everything is ok you can close this ticket.

**Comment by xfreed** [comment]
Update site to the latest changes. This bug still exists.
![image](https://user-images.githubusercontent.com/16673327/82265144-00ad5300-996f-11ea-91dd-ccb8302802db.png)
Attaching log

> |ERROR|EPlast.Controllers.AccountController|User id is null

Set this issue as bug
